FROM node:19-alpine3.16 as dev
WORKDIR /app

ENV DEVELOPMENT_PORT=$DEVELOPMENT_PORT
CMD ["sh", "-c", "echo $DEVELOPMENT_PORT && rm -rf node_modules && npm i && npm run dev -- --host 0.0.0.0 --port $DEVELOPMENT_PORT"]